{{- define "ApplicationSet" -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  {{- $baseMetadata := (($.Values).base).metadata }}
  name: {{ print ($baseMetadata.prefix_name | default "" .appKey ) }}
  namespace: {{ $baseMetadata.namespace | default "argocd" }}
spec:
  {{- $baseSpec := (($.Values).base).spec }}
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    project: {{ $baseSpec.project | default "default" }}
    destination:
      server: {{ $baseSpec.destination.server | default "https://kubernetes.default.svc" }}
      namespace: {{ $baseSpec.destination.namespace | default (dig "app" "metadata" "name" "" .) | default .appKey }}
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
{{- end }}


{{- $tplApps := tpl (.Values.appsSet_dict_tpl_string | default "null") . -}}

{{- $appsDictTpl := dict }}
{{- range $parentKey, $dict := .Values.appsSet_dict_tpl }}
  {{- $newApps := dict }}
  {{- range $subKey, $subValue := $dict }}
    {{- $hashedKey := $subKey }}
    {{- if or $.Values.appsSet_dict_tpl_gen_id $subValue.gen_id }}
      {{- $hashedKey = printf "%s-%s" $subKey (adler32sum $parentKey) }}
    {{- end }}
    {{- $newApps = merge $newApps (dict $hashedKey $subValue) }}
  {{- end }}
  {{- $appsDictTpl = merge $appsDictTpl $newApps }}
{{- end }}

{{- $appsDict := dict }}
{{- range $parentKey, $dict := .Values.appsSet_dict }}
  {{- $newApps := dict }}
  {{- range $subKey, $subValue := $dict }}
    {{- $hashedKey := $subKey }}
    {{- if or $.Values.appsSet_dict_tpl_gen_id $subValue.gen_id }}
      {{- $hashedKey = printf "%s-%s" $subKey (adler32sum $parentKey) }}
    {{- end }}
    {{- $newApps = merge $newApps (dict $hashedKey $subValue) }}
  {{- end }}
  {{- $appsDict = merge $appsDict $newApps }}
{{- end }}

{{- $appsMerged := merge (.Values.apps | default dict) $appsDict (fromYaml $tplApps) $appsDictTpl -}}

{{- range $appKey, $app := $appsMerged }}
  {{- if ne $app nil }}
    {{- if or (not $app.condition) (and $app.condition (eq "true" (tpl (printf "{{%s}}" $app.condition) $))) }}
---
{{- $templateBackup := $app.spec.template -}}
{{- $_ := set $app.spec "template" nil -}}
{{- $appEvaluated := fromYaml (include "tplLeafs" (list (toYaml $app) $)) }}
{{- $_ := set $appEvaluated.spec "template" $templateBackup -}}
{{- $_ := set $appEvaluated.spec "generators"
      (fromYaml (include "transform.generators" $appEvaluated.spec)).generators
-}}
{{- $ApplicationSet := fromYaml (include "ApplicationSet" (dict "appKey" $appKey "app" $appEvaluated "Values" .)) -}}
{{- $ApplicationSet := merge $appEvaluated $ApplicationSet -}}
{{ toYaml $ApplicationSet }}
    {{- end }}
  {{- end }}
{{- end }}
