{{- define "ApplicationSet" -}}
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  {{- $baseMetadata := (($.Values).base).metadata }}
  name: {{ print ($baseMetadata.prefix_name | default "" .appKey ) }}
  namespace: {{ $baseMetadata.namespace | default "argocd" }}
spec:
  {{- $baseSpec := (($.Values).base).spec }}
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  template:
    project: {{ $baseSpec.project | default "default" }}
    destination:
      server: {{ $baseSpec.destination.server | default "https://kubernetes.default.svc" }}
      namespace: {{ $baseSpec.destination.namespace | default (dig "app" "metadata" "name" "" .) | default .appKey }}
    syncPolicy:
      automated:
        prune: true
        selfHeal: true
      syncOptions:
        - CreateNamespace=true
        - ServerSideApply=true
{{- end }}


{{- define "transform.generators" -}}
{{- $spec := . -}}

{{- if and $spec.generators (kindIs "map" $spec.generators) }}

  {{- $out := list -}}

  {{- range $genName, $genValue := $spec.generators }}

    {{- if and $genValue.elements (kindIs "map" $genValue.elements) }}

      {{- $elements := list -}}

      {{- range $name, $cfg := $genValue.elements }}
        {{- $item := dict "name" $name -}}

        {{- range $k, $v := $cfg }}
          {{- $_ := set $item $k $v -}}
        {{- end }}

        {{- $elements = append $elements $item -}}
      {{- end }}

      {{- $out = append $out (dict "list" (dict "elements" $elements)) -}}

    {{- end }}

  {{- end }}

  {{- /* Si transformation vide → fallback */ -}}
  {{- if gt (len $out) 0 }}
    {{- dict "generators" $out | toYaml -}}
  {{- else }}
    {{- dict "generators" $spec.generators | toYaml -}}
  {{- end }}

{{- else }}

  {{- /* Déjà une liste ou absent → on ne touche à rien */ -}}
  {{- dict "generators" $spec.generators | toYaml -}}

{{- end }}

{{- end }}


{{- /* Fonction récursive pour appliquer tpl sur chaque feuille string */ -}}
{{- define "tplLeafs" -}}
  {{- $in := index . 0 -}}
  {{- $ctx := index . 1 -}}
  {{- if (kindIs "map" $in) -}}
    {{- $out := dict -}}
    {{- range $k, $v := $in -}}
      {{- $_ := set $out $k (include "tplLeafs" (list $v $ctx)) -}}
    {{- end -}}
    {{- $out -}}
  {{- else if (kindIs "slice" $in) -}}
    {{- $out := list -}}
    {{- range $v := $in -}}
      {{- $out = append $out (include "tplLeafs" (list $v $ctx)) -}}
    {{- end -}}
    {{- $out -}}
  {{- else if (kindIs "string" $in) -}}
    {{- tpl $in $ctx -}}
  {{- else -}}
    {{- $in -}}
  {{- end -}}
{{- end }}

{{- /* Fonction récursive pour appliquer tpl sur chaque feuille string */ -}}
{{- define "tplLeafs_excludeTemplate" -}}
  {{- $in := index . 0 -}}
  {{- $ctx := index . 1 -}}
  {{- $path := index . 2 | default (list) -}}

  {{- if kindIs "map" $in -}}
    {{- $out := dict -}}
    {{- range $k, $v := $in -}}
      {{- $p := append $path $k -}}
      {{- $_ := set $out $k (ternary
            $v
            (include "tplLeafs_excludeTemplate" (list $v $ctx $p))
            (and (eq (len $p) 2) (eq (index $p 0) "spec") (eq (index $p 1) "template"))
      ) -}}
    {{- end -}}
    {{- $out -}}

  {{- else if kindIs "slice" $in -}}
    {{- $out := list -}}
    {{- range $v := $in -}}
      {{- $out = append $out (include "tplLeafs_excludeTemplate" (list $v $ctx $path)) -}}
    {{- end -}}
    {{- $out -}}

  {{- else if kindIs "string" $in -}}
    {{- tpl $in $ctx -}}

  {{- else -}}
    {{- $in -}}
  {{- end -}}
{{- end }}

{{- $tplApps := tpl (.Values.appsSet_dict_tpl_string | default "null") . -}}

{{- $appsDictTpl := dict }}
{{- range $parentKey, $dict := .Values.appsSet_dict_tpl }}
  {{- $newApps := dict }}
  {{- range $subKey, $subValue := $dict }}
    {{- $hashedKey := $subKey }}
    {{- if or $.Values.appsSet_dict_tpl_gen_id $subValue.gen_id }}
      {{- $hashedKey = printf "%s-%s" $subKey (adler32sum $parentKey) }}
    {{- end }}
    {{- $newApps = merge $newApps (dict $hashedKey $subValue) }}
  {{- end }}
  {{- $appsDictTpl = merge $appsDictTpl $newApps }}
{{- end }}

{{- $appsDict := dict }}
{{- range $parentKey, $dict := .Values.appsSet_dict }}
  {{- $newApps := dict }}
  {{- range $subKey, $subValue := $dict }}
    {{- $hashedKey := $subKey }}
    {{- if or $.Values.appsSet_dict_tpl_gen_id $subValue.gen_id }}
      {{- $hashedKey = printf "%s-%s" $subKey (adler32sum $parentKey) }}
    {{- end }}
    {{- $newApps = merge $newApps (dict $hashedKey $subValue) }}
  {{- end }}
  {{- $appsDict = merge $appsDict $newApps }}
{{- end }}

{{- $appsMerged := merge (.Values.apps | default dict) $appsDict (fromYaml $tplApps) $appsDictTpl -}}

{{- range $appKey, $app := $appsMerged }}
  {{- if ne $app nil }}
    {{- if or (not $app.condition) (and $app.condition (eq "true" (tpl (printf "{{%s}}" $app.condition) $))) }}
---
{{- $templateBackup := $appEvaluated.spec.template -}}   # 1️⃣ mettre de côté
{{- $_ := set $appEvaluated.spec "template" nil -}}
{{- $appEvaluated := fromYaml (include "tplLeafs" (list (toYaml $app) $)) }}
{{- $_ := set $appEvaluated.spec "template" $templateBackup -}}
{{- $_ := set $appEvaluated.spec "generators"
      (fromYaml (include "transform.generators" $appEvaluated.spec)).generators
-}}
{{- $ApplicationSet := fromYaml (include "ApplicationSet" (dict "appKey" $appKey "app" $appEvaluated "Values" .)) -}}
{{- $ApplicationSet := merge $appEvaluated $ApplicationSet -}}
{{ toYaml $ApplicationSet }}
    {{- end }}
  {{- end }}
{{- end }}
