{{- $tplApps := ( tpl (.Values.apps_tpl_string | default "null" ) .)  -}}
{{- $appsMerged := merge (.Values.apps | default (dict) ) (fromYaml $tplApps ) -}}

{{ range $appKey, $app := $appsMerged }}
  {{- if ne $app nil }}
    {{- if or (not $app.condition) (and $app.condition (eq "true" (tpl (printf "{{%s}}" $app.condition) $))) }}
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ $.Values.base.prefix_name_application | default "" }}{{ if (hasKey $app "metadata") }}{{$app.metadata.name}}{{- else }}{{ $appKey }}{{ end }}
  namespace: {{ if (hasKey $app "metadata") }}{{$app.metadata.namespace}}{{- else }}{{ default $.Values.base.metadata.namespace | default "argocd" }}{{ end }}
  annotations:
    {{- if (hasKey $app "metadata") }}{{- $app.metadata.annotations | default (dict) | toYaml | nindent 4 }}{{- else }}{{ dict | toYaml | nindent 4  }}{{ end }} 
  labels:
    {{- if (hasKey $app "metadata") }}{{- $app.metadata.labels | default (dict) | toYaml | nindent 4 }}{{- else }}{{ dict | toYaml | nindent 4  }}{{ end }} 
{{- if $app.force }}
operation:
  sync:
    syncStrategy:
      hook:
        force: true
{{- end }}
spec:
  ignoreDifferences:
    {{- $app.spec.ignoreDifferences | default $.Values.base.spec.ignoreDifferences | default (list) | toYaml | nindent 4 }}
  sources:
    {{- range $sources := $app.spec.sources }}
    - repoURL: {{ $sources.repoURL  }}
      path: {{ $sources.path | default "null" }}
      chart: {{ $sources.chart | default "null" }}
      targetRevision: {{ $sources.targetRevision }}
      plugin:
        {{- $sources.plugin  | toYaml | nindent 8 }}
      helm:
        valueFiles:
          {{- $sources.helm.valueFiles | default (list) | toYaml | nindent 10 }}
        values: |
          {{- tpl ( $sources.helm.values | default "" | toString ) $ | nindent 10 }}
        valuesObject:
          {{- $sources.helm.valuesObject | toYaml | nindent 10 }}
        parameters:
          {{- $sources.helm.parameters | toYaml | nindent 10 }}
      ref: {{ $sources.ref | default "null" }}   
    {{- end }}
  project: {{ if (hasKey $app "metadata") }}{{ $app.metadata.project}}{{- else }}{{ $.Values.base.spec.project | default "default" }}{{ end }}
  destination:
    server: {{ if and (hasKey $app.spec "destination") (hasKey $app.spec.destination "server")}}{{$app.spec.destination.server}}{{- else }}{{ $.Values.base.spec.destination.server }}{{ end }}
    namespace: {{ if and (hasKey $app.spec "destination") (hasKey $app.spec.destination "namespace")}}{{$app.spec.destination.namespace}}{{- else }}{{ if and (hasKey $.Values.base.spec "destination") (hasKey $.Values.base.spec.destination "namespace")}}{{ $.Values.base.spec.destination.namespace }}{{- else }}{{ if (hasKey $app "metadata") }}{{$app.metadata.name}}{{- else }}{{ $appKey }}{{ end }}{{ end }}{{ end }}
  syncPolicy:
    {{- $defaultSyncPolicy := dict "automated" (dict "prune" true "selfHeal" true) "syncOptions" (list "CreateNamespace=true") }}
    {{- $app.spec.syncPolicy | default $.Values.base.spec.syncPolicy | default $defaultSyncPolicy | toYaml | nindent 4 }}
    {{- end }}
  {{- end }}
{{- end }}
